#!/usr/bin/env python3
"""
build_llmpedia_site.py — Build a static LLMPedia site from a run directory.

Professional MediaWiki-inspired responsive static site.

Key features:
  - Robust wikilink handling: unclosed [[ are resolved or cleaned
  - No image placeholder: infobox skips image row if none available
  - Infobox image fields (image.png etc.) stripped; only real downloaded images used
  - Model logo badge on every article
  - Site-wide nav dropdown to switch between encyclopedias
  - Dual nav: back to main portal + current encyclopedia
  - TOC auto-generated from == headings ==
  - Fully responsive (phone → monitor)

Usage:
    python3 build_llmpedia_site.py /path/to/run
    python3 build_llmpedia_site.py /path/to/run --clean --workers 32
    python3 build_llmpedia_site.py /path/to/run --mode anonymous
    python3 build_llmpedia_site.py /path/to/run --global-images /path/to/deploy/image_store
"""
from __future__ import annotations

import argparse
import csv as _csv
import html
import json
import os
import re
import shutil
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ============================================================
#  Config
# ============================================================

DEFAULT_FEATURED_SUBJECTS = [
    "TU Dresden", "Dresden", "Albert Einstein", "ScaDS.AI", "Germany",
]
BROWSE_CHUNK_SIZE   = 600
SEARCH_RESULT_LIMIT = 50
MIN_TOKEN_LEN       = 2
STOPWORDS = {
    "the","and","or","of","to","in","a","an","for","on","with","by","as",
    "is","are","was","were","be","been","it","its","that","this","from",
    "at","which","also","into","than","their","his","her","they","them",
    "he","she","we","you","i","our","your",
}
TAGLINE         = "The first transparent, open encyclopedia generated by LLMs"
IMAGE_STORE_DIR = "image_store"
DEFAULT_WORKERS = 8

_SCRIPT_DIR      = Path(__file__).resolve().parent
LOGO_SEARCH_DIRS = [_SCRIPT_DIR / "logos", _SCRIPT_DIR / "static" / "img", _SCRIPT_DIR]
LOGO_CANDIDATES  = {
    "scads_ai": ["scads_ai.png", "scads_ai.svg", "scads.ai.png", "scads.png", "ScaDS.AI.png"],
}

_MODEL_KEY_DISPLAY = {
    "gpt-5-mini":          "GPT-5-mini",
    "gpt-4.1-mini":        "GPT-4.1-mini",
    "scads-llama-3.3-70b": "Llama 3.3-70B",
    "scads-DeepSeek-V3.2": "DeepSeek V3.2",
}
_MODEL_KEY_LOGO = {
    "gpt-5-mini":          "gpt.png",
    "gpt-4.1-mini":        "gpt.png",
    "scads-llama-3.3-70b": "llama.png",
    "scads-DeepSeek-V3.2": "deepseek.png",
}
_MODEL_DISPLAY_LOGO = {
    "GPT-5-mini":    "gpt.png",
    "GPT-4.1-mini":  "gpt.png",
    "Llama 3.3-70B": "llama.png",
    "DeepSeek V3.2": "deepseek.png",
}

# ── Infobox image field keys to ALWAYS strip ──────────────────
#    These fields reference filenames in wikitext (e.g. image = Berlin.jpg)
#    that don't exist locally. We use the downloaded image cache instead.
_INFOBOX_IMAGE_KEYS = {
    "image", "image_name", "image_file", "image_size", "image_caption",
    "image_alt", "image_width", "image_map", "image1", "image2", "image3",
    "photo", "picture", "img", "logo", "logo_size", "logo_alt", "logo_caption",
    "flag", "flag_size", "flag_alt", "coat_of_arms", "seal", "seal_size",
    "map", "map_image", "map_size", "map_caption", "map_alt",
    "map_image1", "map_image2", "pushpin_map", "pushpin_map_caption",
    "imagename", "imagesize", "imagecaption",
    "blank_emblem", "shield", "coa_image", "symbol",
    "image_skyline", "image_flag", "image_seal", "image_shield",
    "image_blank_emblem", "native_name_image",
}

# Regex to detect bare image filenames as values  (e.g. "Berlin_skyline.jpg")
_IMAGE_FILENAME_RE = re.compile(
    r'^[\w\s\-\.\(\)]+\.(png|jpg|jpeg|svg|gif|webp|tif|tiff)$', re.IGNORECASE
)


# ============================================================
#  Helpers
# ============================================================

def _safe_int(x, default=0):
    try:    return int(x)
    except: return default

def slugify(title: str) -> str:
    title = title.strip().replace(" ", "_")
    return re.sub(r"[^\w\-\.\(\)]+", "_", title)

def load_articles(run_dir: Path) -> List[dict]:
    for name in ("articles.jsonl", "articles_wikitext.jsonl"):
        path = run_dir / name
        if path.exists():
            articles = []
            with path.open("r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line: continue
                    try:
                        obj = json.loads(line)
                        if "subject" in obj and "wikitext" in obj:
                            articles.append(obj)
                    except json.JSONDecodeError:
                        continue
            return articles
    raise FileNotFoundError(f"No articles.jsonl or articles_wikitext.jsonl in {run_dir}")


# ============================================================
#  run_meta.json + model logo
# ============================================================

def load_run_meta(run_dir: Path) -> dict:
    p = run_dir / "run_meta.json"
    if not p.exists(): return {}
    try: return json.loads(p.read_text(encoding="utf-8"))
    except Exception: return {}

def extract_model_key(meta: dict) -> str:
    return (
        (meta.get("args_raw") or {}).get("elicit_model_key") or
        (meta.get("cascading_defaults") or {}).get("global_model_key") or
        (meta.get("args_raw") or {}).get("model_key") or ""
    )

def extract_model_display(meta: dict) -> str:
    raw = extract_model_key(meta)
    return _MODEL_KEY_DISPLAY.get(raw, raw) if raw else ""

def get_model_logo_filename(meta: dict) -> Optional[str]:
    raw = extract_model_key(meta)
    if raw and raw in _MODEL_KEY_LOGO:
        return _MODEL_KEY_LOGO[raw]
    display = extract_model_display(meta)
    return _MODEL_DISPLAY_LOGO.get(display)

def copy_model_logo_to_site(out_dir: Path, logo_filename: Optional[str]) -> Optional[str]:
    if not logo_filename: return None
    src = _SCRIPT_DIR / "static" / "img" / "models" / logo_filename
    if not src.exists(): return None
    dst_dir = out_dir / "static" / "img"
    dst_dir.mkdir(parents=True, exist_ok=True)
    dst = dst_dir / logo_filename
    if not dst.exists():
        shutil.copy2(src, dst)
    return f"static/img/{logo_filename}"


# ============================================================
#  Funnel loading
# ============================================================

def load_funnel_data(run_dir: Path) -> Dict[str, dict]:
    candidates = [
        run_dir / "funnel_analysis" / "entity_funnel.csv",
        run_dir / "funnel_analysis" / "funnel_per_entity.csv",
    ]
    csv_path = next((p for p in candidates if p.exists()), None)
    if csv_path is None:
        print(f"  warning: No funnel data")
        return {}
    meta: Dict[str, dict] = {}
    with csv_path.open("r", encoding="utf-8") as f:
        for row in _csv.DictReader(f):
            subject = (row.get("subject") or "").strip()
            if not subject: continue
            def _i(k): return _safe_int(row.get(k, 0))
            raw_cands  = _i("raw_candidates") or _i("canonical_pre_ner_input") or _i("ner_candidates")
            canon_kept = _i("after_canonical_dedup") or _i("canonical_kept")
            meta[subject] = {
                "subject": subject, "hop": _i("hop"),
                "parent_subject": row.get("parent_subject") or None,
                "raw_candidates": raw_cands,
                "after_canonical_dedup": canon_kept,
                "rejected_canonical": max(raw_cands - canon_kept, 0),
                "ner_accepted": _i("ner_accepted"),
                "ner_rejected_not_ne": _i("ner_rejected_not_ne"),
                "ner_rejected_low_conf": _i("ner_rejected_low_conf"),
                "ner_rejected_parse": _i("ner_rejected_parse") or _i("ner_rejected_parse_fail"),
                "ner_rejected_other": _i("ner_rejected_other"),
                "rejected_by_ner": _i("rejected_by_ner") or _i("ner_rejected"),
                "enqueued_children": _i("enqueued_children") or _i("inserted_children"),
                "rejected_by_similarity": _i("rejected_by_similarity") or _i("similarity_rejected"),
            }
    print(f"  ok Funnel: {len(meta):,} entities")
    return meta


# ============================================================
#  Image handling
# ============================================================

def load_image_cache(run_dir: Path) -> Dict[str, Optional[dict]]:
    cache_path = run_dir / "gptkb_image_cache.json"
    if not cache_path.exists(): return {}
    try: raw = json.loads(cache_path.read_text(encoding="utf-8"))
    except Exception: return {}
    result: Dict[str, Optional[dict]] = {}
    for subject, entry in raw.items():
        if entry is None:
            result[subject] = None
        elif isinstance(entry, dict) and entry.get("store_path"):
            result[subject] = entry
        elif isinstance(entry, str) and entry:
            result[subject] = {"store_path": "", "image_url": entry, "source_url": entry,
                               "license": "", "artist": "", "source": "legacy"}
        else:
            result[subject] = None
    return result

def setup_images_in_site(run_dir: Path, out_dir: Path,
                         global_images: Optional[Path] = None) -> bool:
    dst = out_dir / IMAGE_STORE_DIR
    if dst.exists() or dst.is_symlink(): return True
    src = global_images if global_images else (run_dir / IMAGE_STORE_DIR)
    if not src or not src.exists() or not src.is_dir(): return False
    try:
        os.symlink(src.resolve(), dst); return True
    except (OSError, NotImplementedError): pass
    try:
        shutil.copytree(src, dst); return True
    except Exception as e:
        print(f"  warn: image link failed: {e}"); return False

def get_image_src(entry: Optional[dict]) -> Optional[str]:
    if not entry: return None
    sp = entry.get("store_path", "")
    return sp if sp else (entry.get("image_url") or None)


# ============================================================
#  Logo discovery (ScaDS footer)
# ============================================================

def _find_logo(key: str) -> Optional[Path]:
    for d in LOGO_SEARCH_DIRS:
        for name in LOGO_CANDIDATES.get(key, []):
            p = d / name
            if p.exists(): return p
    return None

def copy_logos_to_site(out_dir: Path) -> Dict[str, Optional[str]]:
    static_img = out_dir / "static" / "img"
    static_img.mkdir(parents=True, exist_ok=True)
    result = {}
    for key in ("scads_ai",):
        src = _find_logo(key)
        if src:
            dest = static_img / src.name
            shutil.copy2(src, dest)
            result[key] = f"static/img/{src.name}"
        else:
            result[key] = None
    return result


# ============================================================
#  Slug + parent maps
# ============================================================

def build_slug_map(articles: List[dict]) -> Dict[str, str]:
    m = {}
    for a in articles:
        s = a["subject"]
        slug = slugify(s)
        m[s] = slug
        m[s.lower()] = slug
    return m

def build_parent_map(articles: List[dict]) -> Dict[str, dict]:
    m = {}
    for a in articles:
        s = a.get("subject")
        if s:
            m[s] = {"parent_subject": a.get("parent_subject"),
                     "parent_hop": a.get("parent_hop"), "hop": a.get("hop", 0)}
    return m


# ============================================================
#  ROBUST wikilink processing
# ============================================================

def _fix_broken_wikilinks(text: str) -> str:
    result_chars = list(text)
    length = len(text)
    open_positions = []
    close_positions = []
    i = 0
    while i < length - 1:
        if text[i] == '[' and text[i+1] == '[':
            open_positions.append(i)
            i += 2
        elif text[i] == ']' and text[i+1] == ']':
            close_positions.append(i)
            i += 2
        else:
            i += 1
    used_closes = set()
    matched_opens = set()
    for op in open_positions:
        for ci, cp in enumerate(close_positions):
            if cp > op and ci not in used_closes:
                used_closes.add(ci)
                matched_opens.add(op)
                break
    insertions = {}
    for op in open_positions:
        if op in matched_opens:
            continue
        content_start = op + 2
        end = content_start
        while end < length:
            if end < length - 1 and text[end] == ']' and text[end+1] == ']':
                break
            if end < length - 1 and text[end] == '[' and text[end+1] == '[':
                break
            if text[end] == '\n':
                break
            end += 1
        link_end = end
        while link_end > content_start and text[link_end-1] in ' \t.,;:!?)':
            link_end -= 1
        if link_end > content_start:
            insertions[link_end] = ']]'
        else:
            insertions[op] = ''
    if not insertions:
        text = _remove_stray_closes(text, open_positions, close_positions)
        return text
    parts = []
    prev = 0
    for pos in sorted(insertions.keys()):
        val = insertions[pos]
        if pos == prev and val == '':
            parts.append(text[prev:pos])
            prev = pos + 2
        else:
            parts.append(text[prev:pos])
            parts.append(val)
            prev = pos
    parts.append(text[prev:])
    text = ''.join(parts)
    text = _remove_stray_closes_simple(text)
    return text

def _remove_stray_closes(text, opens, closes):
    used_closes = set()
    for op in opens:
        for ci, cp in enumerate(closes):
            if cp > op and ci not in used_closes:
                used_closes.add(ci)
                break
    stray = sorted([closes[ci] for ci in range(len(closes)) if ci not in used_closes], reverse=True)
    for pos in stray:
        text = text[:pos] + text[pos+2:]
    return text

def _remove_stray_closes_simple(text):
    result = []
    i = 0
    depth = 0
    while i < len(text):
        if i < len(text) - 1 and text[i] == '[' and text[i+1] == '[':
            depth += 1
            result.append('[[')
            i += 2
        elif i < len(text) - 1 and text[i] == ']' and text[i+1] == ']':
            if depth > 0:
                depth -= 1
                result.append(']]')
            i += 2
        else:
            result.append(text[i])
            i += 1
    return ''.join(result)

def process_inline(text, slug_map):
    text = _fix_broken_wikilinks(text)
    def repl_link(m):
        content = m.group(1)
        if "|" in content:
            target, label = content.split("|", 1)
        else:
            target, label = content, content
        target_page = target.strip()
        label = label.strip()
        if not label:
            label = target_page
        keys = [target_page, target_page.lower()]
        if target_page.startswith("Category:"):
            cat = target_page.split(":", 1)[1].strip()
            keys.extend([cat, cat.lower()])
        href = None
        for k in keys:
            if k in slug_map:
                href = slug_map[k] + ".html"
                break
        if href:
            return f'<a href="{href}">{html.escape(label)}</a>'
        return html.escape(label)
    text = re.sub(r"\[\[(.+?)\]\]", repl_link, text)
    text = text.replace("[[", "").replace("]]", "")
    text = re.sub(r"'''''(.+?)'''''", r"<b><i>\1</i></b>", text)
    text = re.sub(r"'''(.+?)'''", r"<b>\1</b>", text)
    text = re.sub(r"''(.+?)''", r"<i>\1</i>", text)
    def link_url(m):
        url = m.group(0)
        return f'<a href="{url}" target="_blank" rel="noopener noreferrer">{url}</a>'
    text = re.sub(r"https?://[^\s<]+", link_url, text)
    return text

def strip_wiki_markup(wikitext):
    wikitext = re.sub(r"\{\{Infobox[\s\S]+?\}\}", "", wikitext, flags=re.IGNORECASE)
    wikitext = re.sub(r"\{\{[^\n]+}}", "", wikitext)
    def repl(m):
        c = m.group(1)
        return c.split("|", 1)[-1] if "|" in c else c
    wikitext = re.sub(r"\[\[(.+?)\]\]", repl, wikitext)
    wikitext = wikitext.replace("[[", "").replace("]]", "")
    wikitext = wikitext.replace("'''''","").replace("'''","").replace("''","")
    return re.sub(r"\s+", " ", wikitext).strip()


# ============================================================
#  Infobox — NO placeholder, strips image fields, robust links
# ============================================================

def _is_image_field(key: str, val: str) -> bool:
    """Return True if this infobox field is an image reference that should be stripped."""
    key_clean = key.strip().lower().replace(" ", "_")
    # Direct key match
    if key_clean in _INFOBOX_IMAGE_KEYS:
        return True
    # Value looks like a bare image filename
    if _IMAGE_FILENAME_RE.match(val.strip()):
        return True
    # Value starts with "File:" or "Image:" (MediaWiki file references)
    val_lower = val.strip().lower()
    if val_lower.startswith("file:") or val_lower.startswith("image:"):
        return True
    # Value contains only a pixel size like "250px", "300x200px" (image_size leftover)
    if re.match(r'^\d+(\s*x\s*\d+)?\s*px$', val.strip(), re.IGNORECASE):
        return True
    return False


def extract_infobox(wikitext, slug_map, subject, image_entry=None):
    lower = wikitext.lower()
    start = lower.find("{{infobox")
    if start == -1:
        return wikitext, ""
    text = wikitext
    depth = 0; infobox_start = None; end = None; i = start
    while i < len(text) - 1:
        pair = text[i:i+2]
        if pair == "{{":
            depth += 1
            if infobox_start is None: infobox_start = i
            i += 2; continue
        if pair == "}}" and depth > 0:
            depth -= 1; i += 2
            if depth == 0: end = i; break
            continue
        i += 1
    if infobox_start is None or end is None:
        return wikitext, ""
    box_text = text[infobox_start:end]
    rest = text[:infobox_start] + text[end:]
    inner = box_text.strip()
    if inner.startswith("{{"): inner = inner[2:]
    if inner.endswith("}}"): inner = inner[:-2]
    inner = inner.strip()
    if not inner: return rest, ""
    parts = [p.strip() for p in inner.split("|") if p.strip()]
    if not parts: return rest, ""

    fields = []
    for part in parts[1:]:
        if "=" not in part: continue
        key, val = part.split("=", 1)
        key, val = key.strip(), val.strip()
        if not key or not val:
            continue
        # ── SKIP image-related fields ──
        if _is_image_field(key, val):
            continue
        fields.append((key, process_inline(val, slug_map)))
    if not fields: return rest, ""

    rows = [f'<tr><th colspan="2" class="ib-title">{html.escape(subject)}</th></tr>']

    # Image — ONLY from downloaded image cache (never from wikitext fields)
    image_src = get_image_src(image_entry)
    if image_src:
        img_html = (f'<img src="{html.escape(image_src)}" alt="{html.escape(subject)}" '
                    f'class="ib-img" loading="lazy">')
        attr_parts = []
        artist  = (image_entry or {}).get("artist", "")
        lic     = (image_entry or {}).get("license", "")
        lic_url = (image_entry or {}).get("license_url", "")
        src_url = (image_entry or {}).get("source_url", "")
        if artist:  attr_parts.append(html.escape(artist[:80]))
        if lic:
            if lic_url:
                attr_parts.append(f'<a href="{html.escape(lic_url)}" target="_blank">{html.escape(lic)}</a>')
            else:
                attr_parts.append(html.escape(lic))
        if src_url:
            attr_parts.append(f'<a href="{html.escape(src_url)}" target="_blank">source</a>')
        attr_html = f'<div class="ib-attr">{" &middot; ".join(attr_parts)}</div>' if attr_parts else ""
        rows.append(f'<tr><td colspan="2" class="ib-image">{img_html}{attr_html}</td></tr>')

    for key, val_html in fields:
        label = key.replace("_", " ").strip(": ")
        if label: label = label[0].upper() + label[1:]
        rows.append(f'<tr><th>{html.escape(label)}</th><td>{val_html}</td></tr>')

    return rest, '<table class="infobox">\n' + "\n".join(rows) + "\n</table>"


def wikitext_to_html(wikitext, slug_map):
    wikitext = re.sub(r"\{\{[^\n]+}}", "", wikitext)
    lines = wikitext.splitlines()
    html_lines = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            html_lines.append(""); continue
        m = re.match(r"^(=+)\s*(.+?)\s*\1$", stripped)
        if m:
            level = min(len(m.group(1)), 6)
            raw_heading = m.group(2).strip()
            hid = re.sub(r"[^a-z0-9]+", "-", raw_heading.lower()).strip("-")
            heading_html = process_inline(raw_heading, slug_map)
            html_lines.append(f'<h{level} id="{hid}">{heading_html}</h{level}>')
        else:
            html_lines.append(process_inline(line, slug_map))
    result = []; buffer = []
    def flush():
        nonlocal buffer
        if not buffer: return
        p = " ".join(buffer).strip()
        if not p: buffer = []; return
        result.append(p if p.startswith("<h") else f"<p>{p}</p>")
        buffer = []
    for line in html_lines:
        if not line: flush(); continue
        if line.startswith("<h"): flush(); result.append(line)
        else: buffer.append(line)
    flush()
    return "\n".join(result)


# ============================================================
#  TOC
# ============================================================

def extract_toc(body_html):
    headings = re.findall(r'<h(\d)\s+id="([^"]+)"[^>]*>(.+?)</h\d>', body_html)
    if len(headings) < 3:
        return ""
    items = []
    for level, hid, text in headings:
        clean = re.sub(r"<[^>]+>", "", text)
        items.append(f'<li class="toc-l{level}"><a href="#{hid}">{clean}</a></li>')
    return (
        '<div class="toc" id="toc">'
        '<div class="toc-head">Contents '
        '<button class="toc-btn" onclick="this.closest(\'.toc\').classList.toggle(\'collapsed\')">'
        '[hide]</button></div>'
        '<ul>' + "\n".join(items) + '</ul></div>'
    )


# ============================================================
#  Genealogy box
# ============================================================

def _pct(n, d):
    if d <= 0: return ""
    return f"{n/d*100:.1f}%"

def build_genealogy_html(subject, parent_info, funnel, slug_map):
    hop = parent_info.get("hop", 0)
    parent_subject = parent_info.get("parent_subject")
    parts = ['<div class="gen-box">', '<div class="gen-head">Article Genealogy</div>']
    parts.append('<div class="gen-parent">')
    parts.append('<span class="gen-lbl">Parent:</span>')
    if parent_subject:
        ps = slug_map.get(parent_subject) or slug_map.get(parent_subject.lower())
        if ps:
            parts.append(f'<a href="{ps}.html">{html.escape(parent_subject)}</a>')
        else:
            parts.append(f'<span>{html.escape(parent_subject)}</span>')
    else:
        parts.append('<span class="badge seed">SEED</span>')
    parts.append(f'<span class="badge hop">Hop {hop}</span></div>')

    if not funnel or funnel.get("raw_candidates", 0) == 0:
        parts.append('<p class="gen-empty">No expansion data.</p></div>')
        return "\n".join(parts)

    raw   = funnel["raw_candidates"]
    dedup = funnel["after_canonical_dedup"]
    ner   = funnel["ner_accepted"]
    enq   = funnel["enqueued_children"]
    rej_n = funnel["rejected_by_ner"]
    rej_s = funnel["rejected_by_similarity"]

    compact = (f'<span class="fc">Raw <b>{raw}</b> → Dedup <b>{dedup}</b> '
               f'→ NER <b>{ner}</b> → Enqueued <b>{enq}</b></span>')
    parts.append('<details class="fd">')
    parts.append(f'<summary>Expansion Funnel {compact}</summary>')

    def row(l, c, e=""): return f'<div class="fr"><span>{l}</span><span class="fv">{c}{e}</span></div>'
    def sub(l): return f'<div class="fr fs"><span>{l}</span></div>'

    parts.append(row("1. Extracted", raw))
    parts.append(row("2. After dedup", dedup, f" ({_pct(dedup, raw)})"))
    parts.append(row("3. After NER", ner, f" ({_pct(ner, dedup)})"))
    if rej_n > 0:
        d = []
        for k, lbl in [("ner_rejected_not_ne","not NE"),("ner_rejected_low_conf","low conf"),
                        ("ner_rejected_parse","parse"),("ner_rejected_other","other")]:
            v = funnel.get(k, 0)
            if v: d.append(f"{lbl}: {v}")
        parts.append(sub(f'Rejected: {rej_n} ({", ".join(d)})' if d else f'Rejected: {rej_n}'))
    parts.append(row("4. Enqueued", enq, f" ({_pct(enq, ner)})"))
    if rej_s > 0: parts.append(sub(f'Similarity rejected: {rej_s}'))
    overall = _pct(enq, raw)
    if overall:
        parts.append(f'<div class="fr ft"><span><b>Overall</b></span><span class="fv"><b>{overall}</b></span></div>')
    parts.append('</details></div>')
    return "\n".join(parts)


# ============================================================
#  Related links / categories
# ============================================================

def collect_existing_links(article, slug_map):
    raw = article.get("links_from_markup") or []
    existing = []; seen = set()
    for r in raw:
        if not isinstance(r, str): continue
        name = r.strip()
        if not name: continue
        slug = slug_map.get(name) or slug_map.get(name.lower())
        if slug and slug not in seen:
            seen.add(slug); existing.append((name, slug))
    return existing

def collect_existing_categories(article, slug_map):
    raw = article.get("categories_from_markup") or []
    cats = []; seen = set()
    for r in raw:
        if not isinstance(r, str): continue
        name = r.strip()
        if not name: continue
        slug = slug_map.get(name) or slug_map.get(name.lower())
        if slug and slug not in seen:
            seen.add(slug); cats.append((name, slug))
    return cats


# ============================================================
#  LLM note + footer + nav
# ============================================================

def _language_note(anonymous):
    if anonymous:
        return (
            '<div class="ambox"><span class="ambox-i">⚠</span><span>'
            '<b>Note:</b> This article was automatically generated by a '
            'large language model (LLM) from purely parametric knowledge (no retrieval). '
            'It may contain inaccuracies or hallucinations. '
            'This encyclopedia is part of a research project currently under review.'
            '</span></div>')
    return (
        '<div class="ambox"><span class="ambox-i">⚠</span><span>'
        '<b>Note:</b> This article was automatically generated by an LLM and may contain '
        'inaccuracies. See the <a href="https://gptkb.org/" target="_blank">GPTKB project</a>.'
        '</span></div>')

def build_footer_html(logos, anonymous=False):
    def logo_block(key, href, name, sub):
        url = logos.get(key)
        if url:
            return (f'<a href="{href}" target="_blank" rel="noopener noreferrer">'
                    f'<img src="{url}" alt="{name}"></a>')
        return (f'<a href="{href}" target="_blank" rel="noopener noreferrer">'
                f'<span class="ft-lt">{name}<small>{sub}</small></span></a>')
    scads = logo_block("scads_ai", "https://scads.ai/", "ScaDS.AI", "Dresden / Leipzig")
    return f"""<footer class="mw-ft">
  <div class="ft-logos">{scads}</div>
  <div class="ft-links">
    Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>
    <span class="ft-sep">&middot;</span><a href="accessibility.html">Accessibility</a>
    <span class="ft-sep">&middot;</span><a href="imprint.html">Imprint</a>
    <span class="ft-sep">&middot;</span><a href="data_protection.html">Data Protection</a>
  </div>
  <div class="ft-ver">LLMPedia v1</div>
</footer>"""


def _nav_html(model_display, model_logo_path):
    """Build the nav bar with a placeholder for the site-switcher dropdown.
    The dropdown is populated by site_nav.js (written by build_all_sites.py)."""
    logo_html = f'<img src="{model_logo_path}" alt="" class="nav-mlogo">' if model_logo_path else ""
    label = html.escape(model_display) if model_display else "LLMPedia"
    return f"""<nav class="mw-nav">
  <a href="../index.html" class="nav-link nav-home">&#127968; LLMPedia Home</a>
  <span class="nav-sep">|</span>
  <a href="index.html" class="nav-link nav-cur">{logo_html}{label}</a>
  <div class="nav-spacer"></div>
  <div class="nav-dd" id="siteNavDD">
    <button class="nav-dd-btn" onclick="this.parentElement.classList.toggle('open')">
      &#9776; Switch Encyclopedia <span class="nav-dd-arrow">&#9662;</span>
    </button>
    <div class="nav-dd-content" id="siteNavContent">
      <div class="nav-dd-loading">Loading…</div>
    </div>
  </div>
</nav>"""


# ============================================================
#  CSS — with dropdown nav + responsive
# ============================================================

MEDIAWIKI_CSS = r"""
*,*::before,*::after{box-sizing:border-box}
html{font-size:16px;-webkit-text-size-adjust:100%}
body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Liberation Sans",Helvetica,Arial,sans-serif;color:#202122;background:#f6f6f6;line-height:1.65}
a{color:#0645ad;text-decoration:none}a:hover{text-decoration:underline}
img{max-width:100%;height:auto}

.mw-page{max-width:1060px;margin:0 auto;background:#fff;min-height:100vh;display:flex;flex-direction:column;border-left:1px solid #a7d7f9;border-right:1px solid #a7d7f9}

/* ── Nav bar with dropdown ── */
.mw-nav{background:linear-gradient(180deg,#f4f4f4,#eaecf0);border-bottom:1px solid #c8ccd1;padding:.4rem 1.5rem;font-size:.82rem;display:flex;align-items:center;gap:.5rem;flex-wrap:wrap;position:relative;z-index:100}
.nav-link{color:#36c;white-space:nowrap}.nav-link:hover{color:#0645ad}
.nav-home{font-weight:600}
.nav-sep{color:#a2a9b1}
.nav-cur{font-weight:600;color:#202122;display:inline-flex;align-items:center;gap:.3rem}
.nav-mlogo{height:16px;width:auto}
.nav-spacer{flex:1}

/* Dropdown */
.nav-dd{position:relative}
.nav-dd-btn{background:linear-gradient(180deg,#fff,#f0f2f5);border:1px solid #a2a9b1;border-radius:3px;padding:.3rem .7rem;font-size:.8rem;cursor:pointer;color:#202122;display:inline-flex;align-items:center;gap:.35rem;white-space:nowrap;transition:border-color .15s,box-shadow .15s}
.nav-dd-btn:hover{border-color:#36c;box-shadow:0 1px 4px rgba(51,102,204,.15)}
.nav-dd-arrow{font-size:.65rem;transition:transform .2s}
.nav-dd.open .nav-dd-arrow{transform:rotate(180deg)}
.nav-dd-content{display:none;position:absolute;right:0;top:100%;margin-top:4px;background:#fff;border:1px solid #c8ccd1;border-radius:4px;box-shadow:0 4px 16px rgba(0,0,0,.12);min-width:260px;max-height:70vh;overflow-y:auto;z-index:200}
.nav-dd.open .nav-dd-content{display:block}
.nav-dd-loading{padding:.8rem;color:#72777d;font-size:.82rem;text-align:center}

/* Dropdown items */
.nav-dd-group{padding:.35rem .6rem;font-size:.7rem;font-weight:700;color:#54595d;text-transform:uppercase;letter-spacing:.04em;background:#f8f9fa;border-bottom:1px solid #eaecf0}
.nav-dd-item{display:flex;align-items:center;gap:.5rem;padding:.5rem .8rem;font-size:.84rem;color:#202122;border-bottom:1px solid #f0f0f0;transition:background .1s}
.nav-dd-item:hover{background:#eaf3fb;text-decoration:none}
.nav-dd-item.active{background:linear-gradient(135deg,#eaf3fb,#ddeaf7);font-weight:600;border-left:3px solid #36c}
.nav-dd-item img{height:18px;width:18px;object-fit:contain;border-radius:2px;flex-shrink:0}
.nav-dd-item .ndi-ph{width:18px;height:18px;border-radius:2px;background:#36c;color:#fff;display:flex;align-items:center;justify-content:center;font-size:.7rem;font-weight:700;flex-shrink:0}
.nav-dd-item .ndi-info{display:flex;flex-direction:column}
.nav-dd-item .ndi-name{line-height:1.2}
.nav-dd-item .ndi-count{font-size:.7rem;color:#72777d}

.mw-header{background:linear-gradient(180deg,#fff,#f8f9fa);border-bottom:3px solid #36c;padding:.65rem 1.5rem;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:.5rem}
.site-name{font-family:Linux Libertine,Georgia,"Times New Roman",serif;font-size:1.5rem;font-weight:400;color:#000;letter-spacing:-.01em}
.site-name a{color:inherit}
.site-tagline{font-size:.72rem;color:#54595d;margin-left:.5rem;font-style:italic}
.search-form input{padding:.4rem .6rem;border:1px solid #a2a9b1;border-radius:2px;font-size:.88rem;width:260px;max-width:100%;background:#fff}
.search-form input:focus{border-color:#36c;outline:none;box-shadow:0 0 0 2px rgba(51,102,204,.15)}

.mw-body{flex:1;padding:.8rem 1.5rem 2rem}
.mw-body-title{font-family:Linux Libertine,Georgia,"Times New Roman",serif;font-size:1.85rem;font-weight:400;margin:0 0 .15rem;border-bottom:1px solid #a2a9b1;padding-bottom:.2rem;line-height:1.25}

.model-badge{display:inline-flex;align-items:center;gap:.4rem;background:linear-gradient(135deg,#eaf3fb,#f0f7ff);border:1px solid #a7d7f9;border-radius:3px;padding:.25rem .7rem;font-size:.82rem;color:#36c;margin:.35rem 0 .5rem}
.model-badge img{height:18px;width:auto}
.model-badge b{color:#202122}

.ambox{background:#fef6e7;border:1px solid #e0c486;border-left:3px solid #d4a017;padding:.55rem .8rem;margin:0 0 .8rem;font-size:.84rem;color:#604000;display:flex;align-items:flex-start;gap:.5rem;border-radius:0 2px 2px 0}
.ambox a{color:#604000;text-decoration:underline}.ambox-i{font-size:1.05rem;flex-shrink:0;line-height:1}

.mw-body h2{font-family:Linux Libertine,Georgia,"Times New Roman",serif;font-size:1.5rem;font-weight:400;border-bottom:1px solid #a2a9b1;margin:1.4rem 0 .35rem;padding-bottom:.1rem}
.mw-body h3{font-size:1.12rem;font-weight:bold;margin:1rem 0 .25rem}
.mw-body h4{font-size:1rem;font-weight:bold;margin:.8rem 0 .2rem}
.mw-body p{margin:.35rem 0}

.toc{background:#f8f9fa;border:1px solid #a2a9b1;padding:.6rem 1rem;display:inline-block;margin:.5rem 0 1rem;font-size:.85rem;max-width:100%;border-radius:2px}
.toc-head{font-weight:700;margin-bottom:.25rem;color:#202122}
.toc-btn{background:none;border:none;color:#36c;cursor:pointer;font-size:.78rem;margin-left:.3rem}
.toc ul{margin:0;padding-left:1.2rem;list-style:none}.toc li{margin:.08rem 0}.toc li a{color:#0645ad}
.toc-l3{padding-left:.8rem}.toc-l4{padding-left:1.6rem}
.toc.collapsed ul{display:none}

.infobox{float:right;clear:right;margin:.2rem 0 1rem 1.2rem;border:1px solid #a2a9b1;background:#f8f9fa;border-collapse:collapse;font-size:.84rem;width:280px;max-width:100%}
.infobox th,.infobox td{border:1px solid #a2a9b1;padding:.3rem .5rem;vertical-align:top}
.ib-title{text-align:center;font-size:1.05rem;background:#cedff2;font-weight:700;font-family:Linux Libertine,Georgia,"Times New Roman",serif}
.ib-image{background:#fff;text-align:center;padding:.4rem}
.ib-img{width:100%;height:auto;display:block;border-radius:2px}
.ib-attr{font-size:.68rem;color:#54595d;margin-top:.15rem;text-align:center;line-height:1.3}
.ib-attr a{color:#54595d;text-decoration:underline}

.gen-box{background:linear-gradient(135deg,#f0f6ff,#e8f1fa);border:1px solid #a7d7f9;border-radius:3px;padding:.75rem;margin-bottom:.8rem;font-size:.86rem}
.gen-head{font-weight:700;color:#36c;margin-bottom:.4rem;font-size:.92rem}
.gen-parent{display:flex;align-items:center;gap:.5rem;flex-wrap:wrap;padding:.35rem .55rem;background:#fff;border:1px solid #d0e3f0;border-radius:2px;margin-bottom:.4rem}
.gen-lbl{font-weight:600;color:#54595d}
.gen-empty{color:#72777d;font-style:italic;margin:.2rem 0}
.badge{padding:.1rem .4rem;border-radius:2px;font-size:.73rem;font-weight:600;color:#fff}
.badge.seed{background:#36c}.badge.hop{background:#5b7bb4}
.fd{margin-top:.25rem}
.fd summary{cursor:pointer;user-select:none;padding:.3rem .5rem;border:1px solid #d0e3f0;border-radius:2px;background:#f7fbff;color:#36c;font-weight:600;font-size:.83rem;display:flex;flex-wrap:wrap;align-items:center;gap:.5rem;list-style:none}
.fd summary::-webkit-details-marker{display:none}
.fc{color:#202122;font-weight:400;font-size:.8rem}.fc b{font-weight:700}
.fr{display:flex;justify-content:space-between;padding:.18rem 0;border-bottom:1px dashed #e2e8f0}.fr:last-child{border-bottom:none}
.fs{padding-left:1rem;font-size:.78rem;border-bottom:none;color:#54595d}
.fv{font-weight:600}
.ft{margin-top:.25rem;border-top:1px solid #a7d7f9;padding-top:.25rem}

.related{clear:both;margin-top:1.5rem;padding-top:.8rem;border-top:1px solid #eaecf0;font-size:.88rem}
.related h2{font-size:1.1rem;margin-top:0}.related h3{border:0;margin-top:.6rem;font-size:.92rem}
.related ul{list-style:none;padding:0;margin:.15rem 0;display:flex;flex-wrap:wrap;gap:.25rem}
.related li a{display:inline-block;padding:.15rem .5rem;border:1px solid #c8ccd1;border-radius:2px;background:#f8f9fa;font-size:.8rem;transition:background .1s}
.related li a:hover{background:#eaf3fb;border-color:#a7d7f9;text-decoration:none}

.mw-ft{border-top:1px solid #a2a9b1;padding:.8rem 1.5rem;text-align:center;font-size:.78rem;color:#54595d;background:#f8f9fa}
.ft-logos{display:flex;align-items:center;justify-content:center;gap:2rem;margin-bottom:.4rem}
.ft-logos img{height:36px;max-width:130px;object-fit:contain}
.ft-lt{font-weight:700;font-size:.88rem;color:#202122;line-height:1.2}
.ft-lt small{display:block;font-size:.7rem;font-weight:400;color:#72777d}
.ft-links a{color:#0645ad}.ft-sep{color:#a2a9b1;margin:0 .15rem}
.ft-ver{color:#a2a9b1;font-size:.7rem;margin-top:.25rem}

.feat-section{margin:.8rem 0 1rem}
.feat-section h3{margin:0 0 .5rem;font-size:1rem;color:#36c;font-weight:600}
.feat-scroll{display:flex;gap:.7rem;overflow-x:auto;padding-bottom:.5rem;scroll-snap-type:x mandatory;-webkit-overflow-scrolling:touch}
.feat-scroll::-webkit-scrollbar{height:6px}
.feat-scroll::-webkit-scrollbar-track{background:#f0f0f0;border-radius:3px}
.feat-scroll::-webkit-scrollbar-thumb{background:#a7d7f9;border-radius:3px}
.feat-card{flex:0 0 auto;width:180px;scroll-snap-align:start;background:#fff;border:1px solid #c8ccd1;border-radius:8px;padding:.8rem .7rem;display:flex;flex-direction:column;align-items:center;text-align:center;color:#202122;transition:border-color .15s,box-shadow .15s,transform .15s}
.feat-card:hover{border-color:#36c;box-shadow:0 2px 10px rgba(51,102,204,.12);transform:translateY(-1px);text-decoration:none}
.feat-card .fc-letter{width:40px;height:40px;border-radius:50%;background:linear-gradient(135deg,#36c,#5b7bb4);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:1.1rem;margin-bottom:.4rem}
.feat-card .fc-name{font-weight:600;font-size:.88rem;line-height:1.25;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.feat-card .fc-hop{font-size:.7rem;color:#72777d;margin-top:.15rem}

.sum-box{background:linear-gradient(135deg,#eaf3fb,#f0f7ff);border:1px solid #a7d7f9;border-radius:4px;padding:.8rem;margin:0 0 1rem;font-size:.88rem}
.sum-box h3{margin:0 0 .4rem;color:#36c;font-size:1rem;font-weight:600;border:0}
.sum-box p{margin:.1rem 0;color:#202122}

.browse-section{margin-top:1rem}
#browseList a{display:inline-block;margin:.1rem .5rem .1rem 0;font-size:.86rem}
.btn{padding:.35rem .75rem;border:1px solid #a2a9b1;border-radius:3px;background:#f8f9fa;cursor:pointer;font-size:.86rem;transition:background .1s,border-color .1s}
.btn:hover{background:#eaf3fb;border-color:#a7d7f9}
.result{padding:.4rem 0;border-bottom:1px solid #eaecf0}
.result p{margin:.1rem 0 0;font-size:.8rem;color:#54595d}

/* Cross-model comparison box */
.xm-box{background:linear-gradient(135deg,#f7f0ff,#f0e8ff);border:1px solid #c4b5d9;border-radius:4px;padding:.65rem .8rem;margin-bottom:.8rem;font-size:.84rem}
.xm-head{font-weight:700;color:#6b4c9a;margin-bottom:.4rem;font-size:.88rem;display:flex;align-items:center;gap:.4rem}
.xm-icon{font-size:1rem}
.xm-list{display:flex;flex-wrap:wrap;gap:.4rem;align-items:stretch}
.xm-item{display:inline-flex;align-items:center;gap:.35rem;padding:.3rem .6rem;border-radius:3px;border:1px solid #d4c5e9;background:#fff;font-size:.82rem;color:#202122;transition:all .15s;white-space:nowrap}
.xm-item:hover{border-color:#6b4c9a;background:#f0e8ff;text-decoration:none;transform:translateY(-1px);box-shadow:0 2px 6px rgba(107,76,154,.12)}
.xm-current{background:linear-gradient(135deg,#eae0f5,#ddd0ee);border-color:#b8a0d6;font-weight:600;cursor:default}
.xm-badge{font-size:.62rem;text-transform:uppercase;letter-spacing:.03em;background:#6b4c9a;color:#fff;padding:.08rem .3rem;border-radius:2px;font-weight:700}
.xm-logo{height:16px;width:16px;object-fit:contain;border-radius:2px;flex-shrink:0}
.xm-name{line-height:1.2}
.xm-arrow{color:#6b4c9a;font-weight:700;margin-left:.1rem}
.xm-topic{border-style:dashed}
.xm-ct{border-color:#d4a017;background:#fefbf0}
.xm-ct:hover{border-color:#b8860b;background:#fef6e0}

@media(max-width:720px){
  .mw-nav{padding:.3rem .8rem;font-size:.78rem}
  .nav-spacer{display:none}
  .nav-dd{width:100%;margin-top:.3rem}
  .nav-dd-btn{width:100%;justify-content:center}
  .nav-dd-content{left:0;right:0;min-width:auto}
  .mw-header{padding:.5rem .8rem}
  .site-tagline{display:none}
  .search-form input{width:160px}
  .mw-body{padding:.5rem .8rem 1.5rem}
  .mw-body-title{font-size:1.35rem}
  .infobox{float:none;width:100%;max-width:100%;margin:0 0 .8rem}
  .toc{display:block;width:100%}
  .gen-box{padding:.5rem}
  .mw-ft{padding:.6rem}
  .feat-card{width:150px;padding:.6rem .5rem}
  .xm-list{flex-direction:column}
  .xm-item{width:100%}
}
@media(min-width:1200px){.mw-page{max-width:1200px}}
""".strip()

def write_style_css(out_dir):
    (out_dir / "style.css").write_text(MEDIAWIKI_CSS, encoding="utf-8")


# ============================================================
#  Static pages
# ============================================================

def _page_shell(title, body, footer_html, nav_html=""):
    return (
        f'<!DOCTYPE html>\n<html lang="en"><head><meta charset="utf-8">\n'
        f'<meta name="viewport" content="width=device-width,initial-scale=1">\n'
        f'<title>{html.escape(title)} — LLMPedia</title>\n'
        f'<link rel="stylesheet" href="style.css">\n'
        f'<script src="site_nav.js" defer></script></head><body>\n'
        f'<div class="mw-page">{nav_html}\n'
        f'<header class="mw-header"><div><span class="site-name"><a href="index.html">LLMPedia</a></span>'
        f'<span class="site-tagline">{html.escape(TAGLINE)}</span></div>'
        f'<div class="search-form"><form action="index.html">'
        f'<input type="text" name="q" placeholder="Search LLMPedia…" /></form></div></header>\n'
        f'<div class="mw-body"><h1 class="mw-body-title">{html.escape(title)}</h1>\n'
        f'{body}\n</div>\n{footer_html}\n</div></body></html>')

def build_static_pages(out_dir, logos, anonymous=False, nav_html=""):
    footer = build_footer_html(logos, anonymous)
    pages = {
        "data_protection.html": ("Data Protection Declaration",
            "<p>TU Dresden processes personal data within the framework of this publicly accessible website "
            "only in the form of technically necessary cookies. No tracking cookies are used.</p>"
            "<h2>Contact</h2><p>Data Protection Officer Jens Syckor, TU Dresden. "
            "Email: <a href='mailto:informationssicherheit@tu-dresden.de'>informationssicherheit@tu-dresden.de</a></p>"),
        "imprint.html": ("Imprint",
            "<p>Operated by ScaDS.AI Dresden/Leipzig as part of the LLMPedia research project.</p>"
            "<p><a href='https://scads.ai/' target='_blank'>https://scads.ai/</a></p>"),
        "accessibility.html": ("Accessibility Statement",
            "<p>This static site uses semantic HTML and is navigable by keyboard and screen readers.</p>"
            "<p>Feedback: <a href='mailto:informationssicherheit@tu-dresden.de'>informationssicherheit@tu-dresden.de</a></p>"),
    }
    for fname, (title, body) in pages.items():
        (out_dir / fname).write_text(_page_shell(title, body, footer, nav_html), encoding="utf-8")


# ============================================================
#  Article page builder
# ============================================================

def make_article_page(article, slug_map, parent_map, funnel_map, logos,
                      image_cache, out_dir, footer_html, nav_html="",
                      model_display="", model_logo_path=None, anonymous=False):
    subject  = article["subject"]
    slug     = slug_map[subject]
    wikitext = article["wikitext"]

    image_entry = image_cache.get(subject)
    cleaned, infobox_html = extract_infobox(wikitext, slug_map, subject, image_entry)
    body_html = wikitext_to_html(cleaned, slug_map)
    toc_html  = extract_toc(body_html)

    parent_info = parent_map.get(subject, {"hop": 0, "parent_subject": None})
    funnel = funnel_map.get(subject)
    genealogy_html = build_genealogy_html(subject, parent_info, funnel, slug_map)

    related_links = collect_existing_links(article, slug_map)
    related_cats  = collect_existing_categories(article, slug_map)
    related_html  = ""
    if related_links or related_cats:
        parts = ['<aside class="related">']
        if related_links:
            li = [f'<li><a href="{s}.html">{html.escape(t)}</a></li>' for t, s in related_links]
            parts.append("<h2>Linked pages</h2><ul>" + "\n".join(li) + "</ul>")
        if related_cats:
            li = [f'<li><a href="{s}.html">{html.escape(t)}</a></li>' for t, s in related_cats]
            parts.append("<h3>Categories</h3><ul>" + "\n".join(li) + "</ul>")
        parts.append("</aside>")
        related_html = "\n".join(parts)

    model_badge = ""
    if model_display:
        logo_img = f'<img src="{model_logo_path}" alt="">' if model_logo_path else ""
        model_badge = f'<div class="model-badge">{logo_img}Generated by <b>{html.escape(model_display)}</b></div>'

    page = (
        f'<!DOCTYPE html>\n<html lang="en"><head><meta charset="utf-8">\n'
        f'<meta name="viewport" content="width=device-width,initial-scale=1">\n'
        f'<title>{html.escape(subject)} — LLMPedia</title>\n'
        f'<link rel="stylesheet" href="style.css">\n'
        f'<script src="site_nav.js" defer></script>\n'
        f'<script src="cross_model.js" defer></script></head><body>\n'
        f'<div class="mw-page">{nav_html}\n'
        f'<header class="mw-header"><div><span class="site-name"><a href="index.html">LLMPedia</a></span>'
        f'<span class="site-tagline">{html.escape(TAGLINE)}</span></div>'
        f'<div class="search-form"><form action="index.html">'
        f'<input type="text" name="q" placeholder="Search LLMPedia…" /></form></div></header>\n'
        f'<div class="mw-body">\n'
        f'<h1 class="mw-body-title">{html.escape(subject)}</h1>\n'
        f'{model_badge}\n'
        f'<div id="crossModelBox" data-subject="{slug}"></div>\n'
        f'{_language_note(anonymous)}\n'
        f'{genealogy_html}\n{infobox_html}\n{toc_html}\n'
        f'{body_html}\n{related_html}\n'
        f'</div>\n{footer_html}\n</div></body></html>')
    (out_dir / f"{slug}.html").write_text(page, encoding="utf-8")
    return slug


# ============================================================
#  Search index
# ============================================================

def tokenize_for_index(text):
    toks = re.findall(r"[a-z0-9]+", text.lower())
    return [t for t in toks if len(t) >= MIN_TOKEN_LEN and t not in STOPWORDS]

def write_search_index_js(out_dir, entries, browse_order):
    titles   = [e["title"]   for e in entries]
    urls     = [e["url"]     for e in entries]
    snippets = [e["snippet"] for e in entries]
    postings = {}
    for idx, e in enumerate(entries):
        seen = set()
        for tok in tokenize_for_index(e["title"] + " " + e["snippet"][:500]):
            if tok in seen: continue
            seen.add(tok)
            postings.setdefault(tok, []).append(idx)
    payload = {"t": titles, "u": urls, "s": snippets, "p": postings,
               "o": browse_order, "chunk": BROWSE_CHUNK_SIZE, "limit": SEARCH_RESULT_LIMIT}
    js = "window.LLM_SEARCH=" + json.dumps(payload, ensure_ascii=False, separators=(",",":")) + ";\n"
    (out_dir / "search_index.js").write_text(js, encoding="utf-8")


# ============================================================
#  Index page
# ============================================================

def make_index_page(entries, articles, slug_map, parent_map, funnel_map, logos,
                    out_dir, nav_html="", anonymous=False, model_display="", model_logo_path=None):
    hop_counts = {}
    for a in articles:
        h = parent_map.get(a["subject"], {}).get("hop", 0)
        hop_counts[h] = hop_counts.get(h, 0) + 1
    hop_summary = ", ".join(f"Hop {h}: {c:,}" for h, c in sorted(hop_counts.items()))

    featured = []; used = set()
    for name in DEFAULT_FEATURED_SUBJECTS:
        slug = slug_map.get(name) or slug_map.get(name.lower())
        if slug and slug not in used:
            featured.append((name, slug, parent_map.get(name, {}).get("hop", 0))); used.add(slug)
    if len(featured) < 15:
        for s in sorted((a["subject"] for a in articles), key=str.lower):
            pi = parent_map.get(s, {})
            if pi.get("hop", 0) == 0 and not pi.get("parent_subject"):
                slug = slug_map.get(s)
                if slug and slug not in used:
                    featured.append((s, slug, 0)); used.add(slug)
                if len(featured) >= 15: break

    feat_html = ""
    if featured:
        cards = []
        for name, slug, hop in featured:
            letter = name[0].upper() if name else "?"
            hlabel = "Seed" if hop == 0 else f"Hop {hop}"
            cards.append(
                f'<a href="{slug}.html" class="feat-card">'
                f'<div class="fc-letter">{letter}</div>'
                f'<div class="fc-name">{html.escape(name)}</div>'
                f'<div class="fc-hop">{hlabel}</div></a>')
        feat_html = '<div class="feat-section"><h3>Featured Articles</h3><div class="feat-scroll">' + "\n".join(cards) + '</div></div>'

    total_raw = sum(f.get("raw_candidates", 0) for f in funnel_map.values())
    total_enq = sum(f.get("enqueued_children", 0) for f in funnel_map.values())
    total_sim = sum(f.get("rejected_by_similarity", 0) for f in funnel_map.values())
    funnel_line = ""
    if total_raw > 0:
        funnel_line = f'<p><b>Pipeline:</b> {total_raw:,} extracted → {total_enq:,} enqueued ({total_sim:,} similarity-rejected)</p>'
    model_line = ""
    if model_display:
        logo_img = f'<img src="{model_logo_path}" alt="" style="height:18px;vertical-align:middle;margin-right:.3rem">' if model_logo_path else ""
        model_line = f'<p><b>Model:</b> {logo_img}{html.escape(model_display)}</p>'

    footer_html = build_footer_html(logos, anonymous)
    sw_json = json.dumps(sorted(STOPWORDS))

    idx = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>LLMPedia</title><link rel="stylesheet" href="style.css">
<script src="search_index.js" defer></script>
<script src="site_nav.js" defer></script></head><body>
<div class="mw-page">{nav_html}
<header class="mw-header"><div><span class="site-name">LLMPedia</span>
<span class="site-tagline">{html.escape(TAGLINE)}</span></div>
<div class="search-form"><input id="searchBox" type="text" placeholder="Search LLMPedia…" autocomplete="off"/></div></header>
<div class="mw-body">
{feat_html}
<div class="sum-box"><h3>Collection Summary</h3>
<p><b>Total articles:</b> {len(articles):,}</p>{model_line}
<p><b>By hop:</b> {hop_summary}</p>{funnel_line}</div>
<section id="searchResults" style="display:none"><h2>Search Results</h2><div id="results"></div></section>
<section class="browse-section"><h2>Browse All Articles</h2>
<button class="btn" id="browseBtn">Show articles</button>
<div id="browseWrap" style="display:none;margin-top:.5rem"><div id="browseList"></div>
<button class="btn" id="moreBtn" style="display:none;margin-top:.5rem">Load more</button></div></section>
</div>{footer_html}</div>
<script>
(function(){{var SW={sw_json};
function tok(q){{var m=q.toLowerCase().match(/[a-z0-9]+/g);if(!m)return[];return m.filter(function(t){{return t.length>={MIN_TOKEN_LEN}&&SW.indexOf(t)<0}})}}
function esc(s){{return s.replace(/[&<>"']/g,function(c){{return{{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}}[c]}})}}
var box=document.getElementById('searchBox'),rc=document.getElementById('results'),ss=document.getElementById('searchResults');
function search(q){{if(!window.LLM_SEARCH)return[];var I=window.LLM_SEARCH,ts=tok(q);if(!ts.length)return[];var sc=new Map();for(var ti=0;ti<ts.length;ti++){{var ids=I.p[ts[ti]];if(!ids)continue;for(var ii=0;ii<ids.length;ii++)sc.set(ids[ii],(sc.get(ids[ii])||0)+1)}}sc.forEach(function(s,id){{var tl=I.t[id].toLowerCase();var b=0;for(var ti=0;ti<ts.length;ti++)if(tl.indexOf(ts[ti])>=0)b+=2;sc.set(id,s+b)}});var a=Array.from(sc.entries());a.sort(function(a,b){{return b[1]-a[1]}});return a.slice(0,I.limit||{SEARCH_RESULT_LIMIT}).map(function(x){{return{{title:I.t[x[0]],url:I.u[x[0]],snippet:I.s[x[0]]}}}})}}
function render(q){{q=q.trim();rc.innerHTML='';if(!q){{ss.style.display='none';return}}var m=search(q);ss.style.display='block';if(!m.length){{rc.innerHTML='<p>No results.</p>';return}}for(var i=0;i<m.length;i++){{var d=document.createElement('div');d.className='result';d.innerHTML='<a href="'+m[i].url+'"><b>'+esc(m[i].title)+'</b></a><p>'+esc(m[i].snippet)+'</p>';rc.appendChild(d)}}}}
box.addEventListener('input',function(e){{render(e.target.value)}});
var p=new URLSearchParams(location.search);if(p.has('q')){{box.value=p.get('q');render(p.get('q'))}}
var bb=document.getElementById('browseBtn'),bw=document.getElementById('browseWrap'),bl=document.getElementById('browseList'),mb=document.getElementById('moreBtn');
var bp=0;function chunk(){{if(!window.LLM_SEARCH)return;var I=window.LLM_SEARCH,o=I.o||[],c=I.chunk||{BROWSE_CHUNK_SIZE},e=Math.min(o.length,bp+c),f=document.createDocumentFragment();for(var i=bp;i<e;i++){{var a=document.createElement('a');a.href=I.u[o[i]];a.textContent=I.t[o[i]];f.appendChild(a);f.appendChild(document.createTextNode(' '))}}bl.appendChild(f);bp=e;mb.style.display=bp<o.length?'inline-block':'none'}}
bb.addEventListener('click',function(){{bw.style.display='block';bb.style.display='none';chunk()}});mb.addEventListener('click',chunk);}})();
</script></body></html>"""
    (out_dir / "index.html").write_text(idx, encoding="utf-8")


# ============================================================
#  Main build
# ============================================================

def build_site_for_run(run_dir, clean=False, no_images=False, workers=DEFAULT_WORKERS,
                       mode="deploy", global_images=None):
    anonymous = (mode == "anonymous")
    out_dir = run_dir / "site"
    if clean and out_dir.exists():
        print(f"  Cleaning {out_dir}"); shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"  Loading articles...")
    articles = load_articles(run_dir)
    print(f"    {len(articles):,} articles")

    funnel_map = load_funnel_data(run_dir)
    run_meta = load_run_meta(run_dir)
    model_display = extract_model_display(run_meta)
    model_logo_fn = get_model_logo_filename(run_meta)
    print(f"    Model: {model_display or '?'}, Logo: {model_logo_fn or 'none'}")

    slug_map   = build_slug_map(articles)
    parent_map = build_parent_map(articles)

    write_style_css(out_dir)
    logos = copy_logos_to_site(out_dir)
    model_logo_path = copy_model_logo_to_site(out_dir, model_logo_fn)
    nav_html = _nav_html(model_display, model_logo_path)
    build_static_pages(out_dir, logos, anonymous, nav_html)
    footer_html = build_footer_html(logos, anonymous)

    image_cache = {}
    if not no_images:
        image_cache = load_image_cache(run_dir)
        images_ok = setup_images_in_site(run_dir, out_dir, global_images)
        found = sum(1 for v in image_cache.values() if v is not None)
        if image_cache:
            print(f"  Images: {found:,}/{len(image_cache):,}{' (linked)' if images_ok else ''}")

    entries = []
    for a in articles:
        subject = a["subject"]; slug = slug_map[subject]
        plain = strip_wiki_markup(a["wikitext"])
        snippet = plain[:250] + ("..." if len(plain) > 250 else "")
        entries.append({"title": subject, "url": f"{slug}.html", "snippet": snippet})

    indexed = list(enumerate(entries))
    indexed.sort(key=lambda it: (parent_map.get(it[1]["title"], {}).get("hop", 0), it[1]["title"].lower()))
    browse_order = [i for i, _ in indexed]

    existing_html = set()
    if not clean:
        for f in out_dir.iterdir():
            if f.suffix == ".html" and f.name not in ("index.html","data_protection.html","imprint.html","accessibility.html"):
                existing_html.add(f.stem)

    to_build = [a for a in articles if slug_map[a["subject"]] not in existing_html]
    skipped = len(articles) - len(to_build)
    if skipped: print(f"  Skipping {skipped:,} existing (--clean to rebuild)")
    print(f"  Building {len(to_build):,} pages (workers={workers})...")

    t0 = time.perf_counter(); built = 0
    if len(to_build) < 50 or workers <= 1:
        for a in to_build:
            make_article_page(a, slug_map, parent_map, funnel_map, logos, image_cache,
                              out_dir, footer_html, nav_html, model_display, model_logo_path, anonymous)
            built += 1
            if built % 10000 == 0: print(f"    {built:,}/{len(to_build):,}...")
    else:
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futs = {pool.submit(make_article_page, a, slug_map, parent_map, funnel_map, logos,
                                image_cache, out_dir, footer_html, nav_html, model_display,
                                model_logo_path, anonymous): a["subject"] for a in to_build}
            for fut in as_completed(futs):
                try: fut.result()
                except Exception as e: print(f"    WARN: {futs[fut]}: {e}")
                built += 1
                if built % 10000 == 0: print(f"    {built:,}/{len(to_build):,}...")

    elapsed = time.perf_counter() - t0
    print(f"  Built {built:,} in {elapsed:.1f}s ({built/elapsed:.0f}/sec)" if elapsed > 0 else f"  Built {built:,}")

    write_search_index_js(out_dir, entries, browse_order)
    make_index_page(entries, articles, slug_map, parent_map, funnel_map, logos, out_dir,
                    nav_html, anonymous, model_display, model_logo_path)
    return out_dir


def find_run_dirs(root):
    if not root.is_dir(): return []
    for name in ("articles.jsonl", "articles_wikitext.jsonl"):
        if (root / name).exists(): return [root]
    found = set()
    for name in ("articles.jsonl", "articles_wikitext.jsonl"):
        for p in root.rglob(name): found.add(p.parent)
    return sorted(found)


def main():
    parser = argparse.ArgumentParser(description="Build LLMPedia static site")
    parser.add_argument("root_path")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--only-first", action="store_true")
    parser.add_argument("--no-images", action="store_true")
    parser.add_argument("--mode", choices=["anonymous", "deploy"], default="deploy")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS)
    parser.add_argument("--global-images", type=str, default=None)
    args = parser.parse_args()

    root = Path(args.root_path).expanduser().resolve()
    if not root.exists() or not root.is_dir():
        raise SystemExit(f"Not a directory: {root}")
    run_dirs = find_run_dirs(root)
    if not run_dirs:
        raise SystemExit(f"No articles found under: {root}")
    if args.only_first:
        run_dirs = run_dirs[:1]
    global_images = Path(args.global_images).resolve() if args.global_images else None
    print(f"Found {len(run_dirs)} run(s)  [mode={args.mode}]")
    for rd in run_dirs: print(f"  - {rd}")
    print()
    for rd in run_dirs:
        print(f"[BUILD] {rd}")
        try:
            out = build_site_for_run(rd, args.clean, args.no_images, args.workers, args.mode, global_images)
            print(f"[OK]   {out / 'index.html'}\n")
        except SystemExit: raise
        except Exception as e:
            import traceback; traceback.print_exc(); print(f"[FAIL] {e}\n")


if __name__ == "__main__":
    main()